name: appchop
description: "AppChop"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_vector_icons: ^2.0.0
  cupertino_icons: ^1.0.2
  firebase_messaging: ^14.1.2
  firebase_core: ^2.3.0
  hive: ^2.2.3
  permission_handler: ^11.2.0
  path_provider: ^2.1.2
  uuid: ^4.3.3
  flutter_zoom_drawer: ^3.1.2
  material_color_gen: ^2.0.0

#  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
#  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true