name: appchop
description: "AppChop"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  firebase_messaging: ^14.1.2
  firebase_core: ^2.3.0
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
#  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true