name: appchop
description: "AppChop"
publish_to: 'none'

version: 1.1.2+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_vector_icons: ^2.0.0
  cupertino_icons: ^1.0.2
  firebase_messaging: ^14.1.2
  firebase_core: ^2.3.0
  hive: ^2.2.3
  dio: ^5.4.1
  http: ^1.2.1
  google_maps_flutter: ^2.6.0
  custom_info_window: ^1.0.1
  permission_handler: ^11.2.0
  path_provider: ^2.1.2
  fluttertoast: ^8.2.4
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1
  custom_radio_grouped_button: ^2.2.1
  adaptive_action_sheet: ^2.0.3
  modal_bottom_sheet: ^3.0.0
  dotted_border: ^2.1.0
  shimmer: ^3.0.0
  shimmer_animation: ^2.1.0+1
  flutter_slidable: ^3.1.0
  animations: ^2.0.11
  uuid: ^4.3.3
  open_file_plus: ^3.4.1
  share_plus: ^4.5.3
  url_launcher: ^6.2.5
  csv: ^6.0.0
  pdf: ^3.10.8
  flutter_pdfview: ^1.3.2
  money_formatter: ^0.0.5
  flutter_simple_calculator: ^2.2.4
  auto_size_text: ^3.0.0
  slider_button: ^2.1.0
  fluttercontactpicker: ^4.7.0
  flutter_zoom_drawer: ^3.1.2
  material_color_gen: ^2.0.0

#  flutter_launcher_icons: ^0.11.0
#  flutter_native_splash: ^2.2.15
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
#  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/home/menu_logo.png
    - assets/home/background.png
    - assets/login/head_login.png
    - assets/zonas/background.png
    - assets/busqueda/fondo.png
    - assets/clientes/search.png